### ISSUE TITLE
Error: Cannot resolve 'file' or 'directory' ../node_modules/emojione/emoji.json

### ISSUE THREAD

**Issue by elado** [tommoor/emojione-picker#34]
Using webpack.

This `import` is not standard:  https://github.com/tommoor/emojione-picker/blob/master/src/picker.jsx#L4

and fails with webpack. If `emojione` is a dependency (and it is), it should be imported as `emojione/emoji.json` without `node_modules`.

I changed it locally and it it indeed loads the json, however there's another bug, hoping this image can show it:

![screen shot 2016-08-16 at 11 59 20 am](https://cloud.githubusercontent.com/assets/51488/17711993/efd490d4-63a8-11e6-8f2e-4949b05d3bcd.png)

Reverting to `< 1.0`.

**Comment by tommoor** [comment]
Thanks @elado I'll blow away node_modules and take a look at this - I was probably referencing an outdated strategy format in dev would be my guess

**Comment by elado** [comment]
In dev you might wanna use `npm link`.
Thanks!

**Comment by tommoor** [comment]
Closed by https://github.com/tommoor/emojione-picker/commit/ec54ce85670af8a63e77ff457c50467182f1dafb

Note: There is a bug in the emojione strategy file which means tones won't appear for some of the emojis until they fix it https://github.com/Ranks/emojione/pull/330. In the meantime I've added a check so that the entire component doesn't fail in this case.
